### ISSUE TITLE
Cannot connect to repository from TV Box

### ISSUE THREAD

**Issue by baltzis** [techecoyote/Install_LooNatics#12]
Although on my Windows 10 the (new) Kodi installation repository and the updated addons were installed without any problems, on my TV Box (Android) I keep getting an error message:
1. I added the source in the File Manager (https://techecoyote.github.io/Install_LooNatics) and no error message appeared when I pressed OK. When a source is unavailable, at this stage a message appears saying that the connection to the source is not possible.
2. I then got to the Package Installer and selected "Install from zip file", and I installed the "repository.loonaticsasylum-22.5.2.zip" file, also without any problem.
3. However, when I get to "Install from Repository" and select the LooNaticsAsylum Repo, I get the message "Could not connect to repository".

Is there something I am doing wrong or is this a problem with the repository? My Internet connection works just fine: two installations on Windows 10 (Desktop and Laptop) use the same connection with no problem.

**Comment by baltzis** [comment]
After several hours, I finally connected and everything seems OK. Sorry for your time.

**Comment by techecoyote** [comment]
I don't read my Email too often, sorry.
Here is a link to my TG group

https://t.me/+BKQ7ntWeJoFjMjVh
________________________________
